server:
  port: 8761  # Default Eureka server port

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false  # This server doesn't register itself
    fetch-registry: false       # Not fetching registry as it's the server
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: eureka-server
  security:
    user:
      name: admin       # Optional: for basic security
      password: password # Optional: for basic security

# Optional: Actuator endpoints configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"