server:
  port: 8888
  ssl: # Enable in production
    enabled: false # Set to true with keystore

spring:
  application:
    name: config-server
  security:
    user:
      name: ${configserver.username}
      password: ${configserver.password}
  cloud:
    config:
      server:
        git:
          uri: https://github.com/harshprince/claimwise
          search-paths: config
          default-label: main
          username: ${GIT_USER:}      # GitHub username (env var)
          password: ${GIT_TOKEN:}     # GitHub PAT (env var)
          clone-on-start: true

configserver:
  username: claimwise   # Default username for config server
  password: 123456      # Default password for config server

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.int}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
