server:
  port: 8081

spring:
  application:
    name: user-service
  config:
    import: configserver:http://localhost:8888
  datasource:
    url: jdbc:mysql://localhost:3306/userdb
    username: root
    password: Godhar@123
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
