server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    config:
      enabled: false
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
            - name: JwtAuthenticationFilter
        
        - id: claim-service
          uri: lb://CLAIM-SERVICE
          predicates:
            - Path=/claim/**
          filters:
            - StripPrefix=1
            - name: JwtAuthenticationFilter

jwt:
  secret-key: "dGhpcy1pcy1hLXN1cGVyLXNlY3VyZS1zZWNyZXQta2V5LTI1Ni1iaXRz" # Base64 encoded 256-bit key
  issuer: "insurance-claim-system"
  expiration: 86400000 # 24 hours in milliseconds