spring:
  application:
    name: auth-service
  config:
    import: optional:configserver:http://localhost:8888
  security:
    user:
      name: claimwise
      password: 123456
  web:
    servlet:
      context-path: /auth  # This is important for gateway routing

server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true